### ISSUE TITLE
Incompatible with Pyramid 1.5

### ISSUE THREAD

**Issue by dnouri** [dnouri/pyramid-tutorial#1]
Frederic from DFF reports that the tutorial no longer works due to the removal of `pyramid_chameleon` from the Pyramid core.

Pyramid's "What's new" document for Pyramid 1.5 explains which steps to take to add back support for Chameleon templates: http://docs.pylonsproject.org/projects/pyramid/en/master/whatsnew-1.5.html#major-backwards-incompatibilities

**Comment by DFF-fred** [comment]
Thanks for filling my comment. I actually prefer to run the stable version (lack of experience in this area) and simply modified in the setup.py in the requires section the line with  'pyramid', into:
    'pyramid==1.4.5',
And that worked just fine! 
Thanks.
